### ISSUE TITLE
Action fails to download 11.0.0.1

### ISSUE THREAD

**Issue by Griefed** [luangong/setup-install4j#33]
Using this action with Install4j version 11.x fails as the download returns a 404.

Example using `11.0.0.1`:
```
##[debug]Evaluating condition for step: 'Run luangong/setup-install4j@v1'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run luangong/setup-install4j@v1
##[debug]Loading inputs
##[debug]Evaluating: secrets.INSTALL4J_LICENSE
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'INSTALL4J_LICENSE'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run luangong/setup-install4j@v1
  with:
    version: 11.0.0.1
    license: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.4-7/x64
    JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.4-7/x64
    GRADLE_ACTION_ID: gradle/actions/setup-gradle
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    DEVELOCITY_INJECTION_INIT_SCRIPT_NAME: gradle-actions.inject-develocity.init.gradle
    DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE: gradle-actions
    GITHUB_DEPENDENCY_GRAPH_ENABLED: false
##[debug]Downloading https://download.ej-technologies.com/install4j/install4j_linux-x64_11_0_0_1.sh
##[debug]Destination install4j_linux-x64_11_0_0_1.sh
##[debug]Failed to download from "https://download.ej-technologies.com/install4j/install4j_linux-x64_11_0_0_1.sh". Code(404) Message(Not Found)
Error: Unexpected HTTP response: 404
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run luangong/setup-install4j@v1
```

Setting `version` to `11.0` doesn't work either, as the action then tries to download `11` from https://download.ej-technologies.com/install4j/install4j_linux-x64_11.sh

Checking the ej-tech website, the download for version 11 points to: 

- Windows: https://download.ej-technologies.com/install4j/install4j_windows-x64_11_0.exe
- macOS: https://download.ej-technologies.com/install4j/install4j_macos_11_0.dmg
- Linux: https://download.ej-technologies.com/install4j/install4j_linux-x64_11_0.sh
- Unix: https://download.ej-technologies.com/install4j/install4j_unix_11_0.sh

**Comment by luangong** [comment]
First, the latest version of install4j is 11.0, not 11.0.0.1. You can't download a version that they haven't released yet.

Second, their version numbers usually contain one or two dots, not three.

Finally, you should specify the version as `version: '11.0'`, not `version: 11`, otherwise the later value will be treated as a integer in YAML. When you specified `version: 11.0.0.1`, YAML is smart enough to know that `11.0.0.1` can't be a number but a string, but when you specified `version: 11`, it was treated as an integer and the action received `'11'` as a string. I will try to make this action "smarter" at a later time. Thank you!

**Comment by Griefed** [comment]
> First, the latest version of install4j is 11.0, not 11.0.0.1.

Ah, I confused the Gradle plugin version with the release verison. My bad.

> You can't download a version that they haven't released yet.

You don't say...

> Finally, you should specify the version as version: '11.0', not version: 11, otherwise the later value will be treated as a integer in YAML. When you specified version: 11.0.0.1, YAML is smart enough to know that 11.0.0.1 can't be a number but a string, but when you specified version: 11, it was treated as an integer and the action received '11' as a string.

I went by the example in the README, which doesn't make use of '' for the version:

```
steps:
  - uses: luangong/setup-install4j@v1
    with:
      version: 10.0.4
      license: ${{ secrets.INSTALL4J_LICENSE }}
```

Using '11.0' for the version did the trick. My apologies for the invlid bug-report!

Cheers,
Griefed
